### ISSUE TITLE
The ".log" file extention gets omitted 

### ISSUE THREAD

**Issue by zigomi** [Coding-Badly/fixed_window_roller_trouble#1]
Apart from the race conditions: 

I've commented out the 
```
// let _ = remove_dir_all("./tmp");
```

and I need it to create log files in the format `static_part{NNNN}.log`. However, the code in this repo will ommit the ".log". Why? What to do to include it?

![Screenshot_2022-03-08_07-35-59](https://user-images.githubusercontent.com/89519556/157220548-0f663e7e-d19f-4d69-a875-ece8bf3b2be9.png)

**Comment by Coding-Badly** [comment]
> ...and I need it to create log files in the format...

By "it" do you mean this example?  Or are you referring to something you wrote?

**Comment by zigomi** [comment]
This example.

**Comment by Coding-Badly** [comment]
This example exists solely to augment [issue #213](https://github.com/estk/log4rs/issues/213).  I believe the `log4rs` crate includes a few examples that are more likely to be closer to what you want.

**Comment by zigomi** [comment]
>  I believe the log4rs crate includes a few examples that are more likely to be closer to what you want.

Why would you believe, if you could simply check it out by youself? There're none that address what I've asked about.

**Comment by Coding-Badly** [comment]
What is it you would like me to check out?

**Comment by zigomi** [comment]
Whatever you've refered to by "...includes a few examples that are more likely..."

**Comment by Coding-Badly** [comment]
Your response is non-actionable.

What do you want?

**Comment by zigomi** [comment]
My response wasn't supposed to be actionable.

What I want has been described in my 1st post.
